- hosts: all
  become: yes
    tasks: 
    - name: install tomcat
      apt: 
        name: tomcat8
        update_cache: yes 
        state: present
    - name: deploy war file 
      get_url:
        url: http://65.0.7.196:8082/artifactory/artifactory-build-info/
        dest: /var/lib/tomcat8/webapps
        username: admin
        password: Jfrog#77