apiVersion: v1
kind: ReplicationController
metadata: 
  name: rc-app  ## RC name 
spec: 
  replicas: 5    ## no. of pods
  selector: 
      app: gol
  template:      ## pod definition 
    metadata: 
      name: pod-tomcat ## Pod Name
      labels: 
        pod: server 
        app: gol  
    spec: 
      containers: 
        - name: app-cont  ## container Name
          image: nginx 
          ports: 
           - containerPort: 80