- hosts: all 
  become: yes 
  vars: 
    package_name: Webserver
  tasks: 
  - name: create directory
    file:
       path: /home/ansible
       state: directory
  - name: copy file from ACS to all nodes 
    copy: 
       src: /home/ansible/test
       dest: /home/ansible/static 
  - name: copy template from ACS to all nodes 
    template: 
       src: /home/ansible/test.j2
       dest: /home/ansible/dynamic